### ISSUE TITLE
[Known Issue] Plugin doesn not seem to load properly on server start

### ISSUE THREAD

**Issue by SystemFiles** [SystemFiles/CBShop-Plugin#7]
The reason for this is unknown and there are no error messages present at the moment. We will add some debug messaging to the plugin temporarily, then determine and fix the problem.

Thanks for your patience,
SystemFiles

**Comment by SystemFiles** [comment]
Still looking for solution to the problem.

**Comment by SystemFiles** [comment]
Error Message:

```
[12:35:58 ERROR]: Could not load 'plugins/CBShop-1.1.5-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Title cannot be longer than 32 characters
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60-ea]
Caused by: java.lang.IllegalArgumentException: Title cannot be longer than 32 characters
    at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom$MinecraftInventory.<init>(CraftInventoryCustom.java:59) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom.<init>(CraftInventoryCustom.java:32) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createInventory(CraftServer.java:1526) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.Bukkit.createInventory(Bukkit.java:937) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    at net.cubebeaters.CBShop.<init>(CBShop.java:44) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60-ea]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_60-ea]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_60-ea]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_60-ea]
    at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_60-ea]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    ... 6 more


```

**Comment by SystemFiles** [comment]
Problem Solved, Issue was in the creation of Inventories. @HeyMitch, You changed the inventory names and they were longer than 16 characters and so the plugin throws a InvalidPluginException.
This problem has since been replicated in beta release 1.2.0
